module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("circles", [
      {
        state: "Andhra Pradesh",
        longitude: "80.231",
        latitude: "16.450",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Assam",
        longitude: "92.547",
        latitude: "26.200",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Bihar",
        longitude: "85.313",
        latitude: "25.096",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Jharkhand",
        longitude: "85.309",
        latitude: "23.344",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Chennai",
        longitude: "80.278",
        latitude: "13.082",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Delhi NCR",
        longitude: "77.102",
        latitude: "28.704",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Gujarat",
        longitude: "72.571",
        latitude: "23.022",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Haryana",
        longitude: "76.085",
        latitude: "29.058",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Himachal Pradesh",
        longitude: "77.173",
        latitude: "31.104",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Jammu Kashmir",
        longitude: "74.797",
        latitude: "34.083",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Karnataka",
        longitude: "76.936",
        latitude: "12.971",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Kerala",
        longitude: "76.271",
        latitude: "10.850",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Kolkata",
        longitude: "88.363",
        latitude: "22.572",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Madhya Pradesh",
        longitude: "77.412",
        latitude: "23.259",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Chhattisgarh",
        longitude: "81.605",
        latitude: "21.251",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Maharashtra",
        longitude: "73.856",
        latitude: "18.520",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Mumbai",
        longitude: "72.877",
        latitude: "19.076",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "North East",
        longitude: "93.376",
        latitude: "24.742",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Orissa",
        longitude: "85.098",
        latitude: "20.951",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Punjab",
        longitude: "75.857",
        latitude: "30.900",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Rajasthan",
        longitude: "75.787",
        latitude: "26.912",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "Tamil Nadu",
        longitude: "78.704",
        latitude: "10.790",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "UP East",
        longitude: "83.018",
        latitude: "25.317",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "UP West",
        longitude: "79.019",
        latitude: "28.667",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        state: "West Bengal",
        longitude: "87.855",
        latitude: "22.986",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },
  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("circles", null, {});
  },
};
